name: plp

services:
  db:
    image: postgres:17
    restart: always
    shm_size: '128mb'
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: plp_database
    secrets:
      - postgres-user
      - postgres-password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - plp-network
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - configuration=Project
    environment:
      ConnectionStrings__MainDatabase: "Host=db:5432;Database=plp_database;Username=${POSTGRES_ROOT_USER};Password=${POSTGRES_ROOT_PWD};"
      ASPNETCORE_URLS: "http://*:5077"
      INDEBUGGER: true # ponastavi bazo ob start up
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - plp-network
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./configs/ssl:/etc/nginx/ssl:ro
    networks:
      - plp-network
    depends_on:
      - server
    ports:
      - 127.0.0.1:3000:80
      - 127.0.0.1:3443:443
    environment:
      SERVER_NAME: localhost
      PROXY_PASS_ADDRESS: http://server:5077/
    

networks:
  plp-network:
    driver: bridge

volumes:
  pgdata:

secrets:
  postgres-user:
    environment: POSTGRES_ROOT_USER
  postgres-password:
    environment: POSTGRES_ROOT_PWD