
services:
  db:
    image: postgres:17
    restart: always
    shm_size: '128mb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plp_database
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - plp-network
  
  server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./PLPServer:/app:ro
      - csobj:/app/obj:rw
      - ./PLPServer/bin:/app/bin:rw
    command: "dotnet watch run --launch-profile httpDocker --non-interactive" # add --non-interactive?
    working_dir: /app
    #tty: true
    #stdin_open: true
    networks:
      - plp-network
    ports:
      - "127.0.0.1:5077:5077"
      #- "127.0.0.1:5443:443"
    develop:
      watch:
        - action: sync
          path: ./PLPServer
          target: /app
          ignore:
            - "*.http"

networks:
  plp-network:
    driver: bridge

volumes:
  pgdata:
  csobj: