// tslint:disable
/**
 * Version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MainPageZapis
 */
export interface MainPageZapis {
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    zacetekVoznje?: string;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    konecVoznje?: string;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    linijaId: string;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    nazivLinije: string | null;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    narocnikId: string;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    nazivNarocnika: string | null;
    /**
     * @type {number}
     * @memberof MainPageZapis
     */
    znesekPogodbe: number;
    /**
     * @type {string}
     * @memberof MainPageZapis
     */
    id: string;
}
