// tslint:disable
/**
 * Version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PogodbaBasic
 */
export interface PogodbaBasic {
    /**
     * @type {string}
     * @memberof PogodbaBasic
     */
    id?: string;
    /**
     * @type {string}
     * @memberof PogodbaBasic
     */
    linijaId?: string;
    /**
     * @type {string}
     * @memberof PogodbaBasic
     */
    prevoznikId?: string;
    /**
     * @type {number}
     * @memberof PogodbaBasic
     */
    znesek?: number;
}
