// tslint:disable
/**
 * Version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * @type {string}
     * @memberof UserInfo
     */
    id?: string;
    /**
     * @type {string}
     * @memberof UserInfo
     */
    userName: string | null;
    /**
     * @type {string}
     * @memberof UserInfo
     */
    email: string | null;
    /**
     * @type {string}
     * @memberof UserInfo
     */
    role?: string | null;
}
