// tslint:disable
/**
 * Version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    LinijaBasic,
} from '../models';

export interface LinijeGetRequest {
    startIndex?: number;
    limit?: number;
}

/**
 * no description
 */
export class LinijeApi extends BaseAPI {

    /**
     */
    linijeGet({ startIndex, limit }: LinijeGetRequest): Observable<Array<LinijaBasic>>
    linijeGet({ startIndex, limit }: LinijeGetRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<LinijaBasic>>>
    linijeGet({ startIndex, limit }: LinijeGetRequest, opts?: OperationOpts): Observable<Array<LinijaBasic> | AjaxResponse<Array<LinijaBasic>>> {

        const query: HttpQuery = {};

        if (startIndex != null) { query['startIndex'] = startIndex; }
        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<LinijaBasic>>({
            url: '/linije',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
