// tslint:disable
/**
 * Version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    PogodbaBasic,
} from '../models';

export interface PogodbeGetRequest {
    startIndex?: number;
    limit?: number;
}

/**
 * no description
 */
export class PogodbeApi extends BaseAPI {

    /**
     */
    pogodbeGet({ startIndex, limit }: PogodbeGetRequest): Observable<Array<PogodbaBasic>>
    pogodbeGet({ startIndex, limit }: PogodbeGetRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<PogodbaBasic>>>
    pogodbeGet({ startIndex, limit }: PogodbeGetRequest, opts?: OperationOpts): Observable<Array<PogodbaBasic> | AjaxResponse<Array<PogodbaBasic>>> {

        const query: HttpQuery = {};

        if (startIndex != null) { query['startIndex'] = startIndex; }
        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<PogodbaBasic>>({
            url: '/pogodbe',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
